import express from 'express';
import { asyncHandler } from '../../middleware/errors.js';
import { authenticate, allowRoles, optionalAuthenticate } from '../../middleware/authMiddleware.js';
import { upload } from '../../middleware/upload.js';
import * as auth from '../../controller/app/authController.js';
import * as user from '../../controller/app/userController.js';
import * as review from '../../controller/app/reviewController.js';

const router = express.Router();
router.post('/auth/register', asyncHandler(auth.register));
router.post('/auth/login', asyncHandler(auth.login));
router.post('/auth/refresh', asyncHandler(auth.refreshToken));
router.get('/settings', asyncHandler(user.settings));
router.get('/classes', asyncHandler(user.classes));
router.get('/faqs', asyncHandler(user.faqs));
router.get('/courses', optionalAuthenticate, asyncHandler(user.courses));
router.get('/courses/:courseId/reviews', asyncHandler(review.list));
router.use(authenticate, allowRoles('user'));
router.get('/search', asyncHandler(user.search));
router.get('/profile', user.profile);
router.patch('/profile', upload.single('avatar'), asyncHandler(user.updateProfile));
router.patch('/profile/preferences', asyncHandler(user.updatePreferences));
router.get('/payments', asyncHandler(user.payments));
router.post('/payments', upload.single('screenshot'), asyncHandler(user.submitPayment));
router.get('/notifications', asyncHandler(user.notifications));
router.post('/notifications/daily-goal', asyncHandler(user.completeDailyGoal));
router.delete('/notifications', asyncHandler(user.clearNotifications));
router.patch('/notifications/read-all', asyncHandler(user.markAllNotificationsRead));
router.patch('/notifications/:id/read', asyncHandler(user.markNotificationRead));
router.delete('/notifications/:id', asyncHandler(user.deleteNotification));
router.get('/chat/presence', asyncHandler(user.chatPresence));
router.get('/chat/messages', asyncHandler(user.chatMessages));
router.post('/chat/messages', asyncHandler(user.sendChatMessage));
router.get('/favorites/videos', asyncHandler(user.favoriteVideos));
router.post('/courses/:courseId/videos/:videoId/like', asyncHandler(user.toggleVideoLike));
router.post('/courses/:courseId/videos/:videoId/progress', asyncHandler(user.updateVideoProgress));
router.post('/courses/:courseId/reviews', asyncHandler(review.save));
export default router;
