import express from 'express';
import { asyncHandler } from '../../middleware/errors.js';
import { authenticate, allowRoles } from '../../middleware/authMiddleware.js';
import { login, logout, refresh } from '../../controller/admin/authController.js';
import { dashboard } from '../../controller/admin/dashboardController.js';
import * as payment from '../../controller/admin/paymentController.js';
import * as user from '../../controller/admin/userController.js';
import { update as updateSettings } from '../../controller/admin/settingController.js';
import * as course from '../../controller/admin/courseController.js';
import * as academyClass from '../../controller/admin/classController.js';
import * as faq from '../../controller/admin/faqController.js';
import * as chat from '../../controller/admin/chatController.js';
import * as adminProfile from '../../controller/admin/profileController.js';
import * as notification from '../../controller/admin/notificationController.js';
import * as review from '../../controller/admin/reviewController.js';
import { courseUpload, upload } from '../../middleware/upload.js';

const router = express.Router();
router.post('/auth/login', asyncHandler(login));
router.post('/auth/refresh', asyncHandler(refresh));
router.post('/auth/logout', asyncHandler(logout));
router.use(authenticate, allowRoles('admin'));
router.get('/profile', asyncHandler(adminProfile.profile));
router.put('/profile', upload.single('avatar'), asyncHandler(adminProfile.update));
router.put('/profile/password', asyncHandler(adminProfile.updatePassword));
router.get('/dashboard', asyncHandler(dashboard));
router.get('/reviews', asyncHandler(review.list));
router.patch('/reviews/:id', asyncHandler(review.moderate));
router.delete('/reviews/:id', asyncHandler(review.remove));
router.get('/notifications', asyncHandler(notification.list));
router.patch('/notifications/read-all', asyncHandler(notification.markAllRead));
router.patch('/notifications/:id/read', asyncHandler(notification.markRead));
router.delete('/notifications', asyncHandler(notification.clear));
router.get('/payments', asyncHandler(payment.list));
router.patch('/payments/:id', asyncHandler(payment.review));
router.get('/users', asyncHandler(user.list));
router.get('/users/:id', asyncHandler(user.details));
router.patch('/users/:id/status', asyncHandler(user.updateStatus));
router.put('/users/:id', asyncHandler(user.update));
router.delete('/users/:id', asyncHandler(user.remove));
router.put('/settings', upload.single('qrImage'), asyncHandler(updateSettings));
router.get('/faqs', asyncHandler(faq.list));
router.post('/faqs', asyncHandler(faq.create));
router.put('/faqs/:id', asyncHandler(faq.update));
router.delete('/faqs/:id', asyncHandler(faq.remove));
router.get('/chats', asyncHandler(chat.conversations));
router.get('/chats/:userId/messages', asyncHandler(chat.messages));
router.post('/chats/:userId/messages', asyncHandler(chat.send));
router.get('/classes', asyncHandler(academyClass.list));
router.get('/classes/:id', asyncHandler(academyClass.details));
router.post('/classes', asyncHandler(academyClass.create));
router.put('/classes/:id', asyncHandler(academyClass.update));
router.delete('/classes/:id', asyncHandler(academyClass.remove));
router.get('/courses', asyncHandler(course.list));
router.post('/courses/upload', courseUpload.single('file'), asyncHandler(course.uploadFile));
router.post('/courses', asyncHandler(course.create));
router.put('/courses/:id', asyncHandler(course.update));
router.delete('/courses/:id', asyncHandler(course.remove));
export default router;
